language: c

matrix:
  include:
    - os: linux

before_install:
  - pip install --user cpp-coveralls

addons:
  apt:
    packages:
    - libarchive-dev
    - libjudy-dev
    - pkg-config

script:
  - ./waf configure
  - ./waf build
  - ./waf test
  - ./waf test_cli

after_success:
  - COV=$(python -c 'import site; print "%s/bin/" % site.USER_BASE'); $COV/coveralls --include src --build-root build/test/
